# syntax=docker/dockerfile:1
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --silent || npm install --silent
COPY . .
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist ./
# Copy custom nginx config to enable SPA fallback
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
