version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: risinglion-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: risinglion
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: risinglion-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: risinglion-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/risinglion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
      # APP_JWT_SECRET: change-me
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: risinglion-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  db_data:
